-- Your SQL goes here
CREATE TABLE device (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(150) NOT NULL,
  manufacturer VARCHAR(150) NOT NULL,
  issue VARCHAR NOT NULL,
  picture VARCHAR,
  type_plate VARCHAR,
  confirmed BOOLEAN NOT NULL DEFAULT 0,
  user INTEGER NOT NULL,
  state INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE,
  FOREIGN KEY (state) REFERENCES state(id) ON DELETE CASCADE
)