-- Your SQL goes here
CREATE TABLE device (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(150) NOT NULL,
  manufacturer VARCHAR(150) NOT NULL,
  issue VARCHAR NOT NULL,
  picture VARCHAR,
  type_plate VARCHAR,
  confirmed BOOLEAN NOT NULL DEFAULT 0,
  guest INTEGER NOT NULL,
  state INTEGER NOT NULL,
  FOREIGN KEY (guest) REFERENCES guest(id) ON DELETE CASCADE,
  FOREIGN KEY (state) REFERENCES state(id) ON DELETE CASCADE
)