-- Your SQL goes here
CREATE TABLE message (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  parent INTEGER NOT NULL,
  content VARCHAR NOT NULL,
  date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  device INTEGER NOT NULL,
  sender INTEGER NOT NULL,
  FOREIGN KEY (parent) REFERENCES message(id) ON DELETE CASCADE,
  FOREIGN KEY (device) REFERENCES device(id) ON DELETE CASCADE,
  FOREIGN KEY (sender) REFERENCES user(id) ON DELETE CASCADE
)