-- Your SQL goes here
CREATE TABLE supporter (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name VARCHAR(150) NOT NULL,
  user INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES user(id) ON DELETE CASCADE
)